#!/usr/bin/env bash

INTERNAL_MONITOR="eDP-1"
EXTERNAL_MONITOR="HDMI-1"

pgrep -x sxhkd > /dev/null || sxhkd &


# On first load, setup default workspaces
if [[ "$1" = 0 ]]; then
  if [[ $(xrandr -q | grep "${EXTERNAL_MONITOR} connected") ]]; then
    bspc monitor "$EXTERNAL_MONITOR" -d 1 2 3 4 5
    bspc monitor "$INTERNAL_MONITOR" -d 6 7 8 9 10
    bspc wm -O "$EXTERNAL_MONITOR" "$INTERNAL_MONITOR"
	feh --no-fehbg --bg-fill ~/.local/share/wall.jpg --bg-fill ~/.local/share/wall.jpg
  else
    bspc monitor "$INTERNAL_MONITOR" -d 1 2 3 4 5 6 7 8 9
	feh --no-fehbg --bg-fill ~/.local/share/wall.jpg
  fi
fi

bspc config border_width         2
bspc config window_gap           11

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc wm -O eDP-1 
bspc monitor eDP-1 -d 1 2 3 4 5 6 7 8  

picom -f &

nm-applet &
dunst &

# Setup monitors, polybar and wallpaper
~/.local/bin/bspwm_setup_monitors.sh &
